from zoneinfo import ZoneInfo

RECOMMENDATION_TIMEZONE = ZoneInfo("Asia/Seoul")

STAGE_0_MAX = 4
STAGE_1_MAX = 9
TODAY_ITEM_COUNT = 5
WEEKLY_WINDOW_DAYS = 7
WEEKLY_ITEM_COUNT = 2

SAVE_EXCLUDE_HOURS = 48
VIEW_EXCLUDE_HOURS = 24
RECOMMEND_EXCLUDE_DAYS = 3

SECONDS_PER_DAY = 86_400
SAVE_SCORE_MAX_DAYS = 30
VIEW_SCORE_MAX_DAYS = 7
RECOMMEND_SCORE_MAX_DAYS = 14
VIEW_COUNT_SCORES = (1.00, 0.75, 0.50, 0.25, 0.10)

WEIGHT_SAVE = 0.20
WEIGHT_LAST_VIEW = 0.30
WEIGHT_VIEW_COUNT = 0.15
WEIGHT_RECENCY = 0.25
WEIGHT_FAVORITE = 0.10

CANDIDATE_TOP_RATIO = 0.30
CANDIDATE_MIN = 10
CANDIDATE_MAX = 30
MAX_SAME_CATEGORY = 2
